import Link from "next/link";
import { ArrowRight, BadgeCheck, FileText, MapPin, SearchCheck } from "lucide-react";
import { PublicHeader } from "@/components/public-header";

const steps = [
  { icon: BadgeCheck, number: "01", title: "Become a member", text: "Register your student membership with your college and city details." },
  { icon: FileText, number: "02", title: "Raise your voice", text: "Submit a problem with the context needed to take it forward." },
  { icon: SearchCheck, number: "03", title: "Stay informed", text: "Use your ticket number to check its progress anytime." },
];

export default function Home() {
  return <div className="min-h-screen bg-[#f7f5ef]"><PublicHeader /><main><section className="texture border-b border-[#dcdcd3] bg-[#e8efe6]"><div className="mx-auto grid max-w-6xl gap-10 px-4 py-16 sm:px-6 lg:grid-cols-[1.15fr_.85fr] lg:py-24"><div className="max-w-2xl"><p className="mb-5 flex items-center gap-2 text-sm font-bold uppercase tracking-[0.14em] text-[#c85d37]"><MapPin size={16} /> Maharashtra student platform</p><h1 className="font-[var(--font-devnagari)] text-4xl font-extrabold leading-tight text-[#10382e] sm:text-6xl">तुमचा आवाज.<br />आमची साथ.</h1><p className="mt-5 max-w-xl text-xl leading-8 text-[#405249]">Membership and grievance support for students across Maharashtra, built to make every concern visible and actionable.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="focus-ring inline-flex min-h-12 items-center justify-center gap-2 rounded-md bg-[#174c3e] px-5 font-bold text-white transition hover:bg-[#10382e]" href="/register">Register as a member <ArrowRight size={18} /></Link><Link className="focus-ring inline-flex min-h-12 items-center justify-center gap-2 rounded-md border border-[#174c3e] bg-[#fffdf8] px-5 font-bold text-[#174c3e] transition hover:bg-[#f5dc9a]" href="/report-issue">Report a problem <FileText size={18} /></Link></div></div><div className="self-end border-l-4 border-[#efb742] bg-[#fffdf8] p-6 shadow-sm"><p className="text-sm font-bold uppercase tracking-[0.12em] text-[#64736b]">Made for students</p><p className="mt-3 text-2xl font-bold leading-tight text-[#174c3e]">A direct path from a student concern to leadership attention.</p><Link href="/track" className="focus-ring mt-6 inline-flex rounded-sm text-sm font-bold text-[#c85d37] underline decoration-2 underline-offset-4">Already submitted a ticket? Track it here.</Link></div></div></section><section className="mx-auto max-w-6xl px-4 py-16 sm:px-6"><div className="mb-8 flex items-end justify-between gap-6"><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-[#c85d37]">How it works</p><h2 className="mt-2 text-3xl font-bold text-[#10382e]">Simple by design</h2></div><p className="hidden max-w-sm text-right text-[#64736b] sm:block">No complicated process. Just the essentials to get help moving.</p></div><div className="grid gap-px overflow-hidden rounded-md border border-[#dcdcd3] bg-[#dcdcd3] md:grid-cols-3">{steps.map(({ icon: Icon, number, title, text }) => <article className="bg-[#fffdf8] p-6" key={number}><span className="text-sm font-bold text-[#c85d37]">{number}</span><Icon className="mt-8 text-[#174c3e]" size={27} strokeWidth={1.7} /><h3 className="mt-5 text-xl font-bold text-[#10382e]">{title}</h3><p className="mt-2 leading-6 text-[#64736b]">{text}</p></article>)}</div></section></main></div>;
}