create extension if not exists pgcrypto;

create sequence if not exists public.member_number_seq;
create sequence if not exists public.ticket_number_seq;
create table public.districts (id uuid primary key default gen_random_uuid(), name text not null unique);
create table public.cities (id uuid primary key default gen_random_uuid(), district_id uuid not null references public.districts(id) on delete cascade, name text not null, unique(district_id, name));
create table public.profiles (id uuid primary key references auth.users on delete cascade, full_name text, phone text unique, role text not null default 'student' check (role in ('student','admin')), city_id uuid references public.cities, district_id uuid references public.districts, scope_district_id uuid references public.districts, scope_city_id uuid references public.cities, created_at timestamptz not null default now());
create table public.members (id uuid primary key default gen_random_uuid(), profile_id uuid not null unique references public.profiles(id) on delete cascade, college_name text not null, course text not null, year_of_study text not null, email text, membership_id text not null unique default ('MSW-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('member_number_seq'::regclass)::text, 6, '0')), status text not null default 'active', created_at timestamptz not null default now());
create table public.tickets (id uuid primary key default gen_random_uuid(), ticket_number text not null unique default ('TCK-' || lpad(nextval('ticket_number_seq')::text, 6, '0')), student_id uuid not null references public.profiles(id), category text not null check (category in ('education','hostel','scholarship','local_issue','other')), description text not null, city_id uuid references public.cities, district_id uuid references public.districts, status text not null default 'new' check (status in ('new','acknowledged','in_progress','resolved','closed')), urgency text not null default 'normal' check (urgency in ('normal','high')), attachment_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.ticket_updates (id uuid primary key default gen_random_uuid(), ticket_id uuid not null references public.tickets(id) on delete cascade, actor_id uuid references public.profiles(id), note text, new_status text check (new_status in ('new','acknowledged','in_progress','resolved','closed')), created_at timestamptz not null default now());

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin') $$;
create or replace function public.set_ticket_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end $$;
create trigger tickets_updated_at before update on public.tickets for each row execute function public.set_ticket_updated_at();

alter table public.districts enable row level security; alter table public.cities enable row level security; alter table public.profiles enable row level security; alter table public.members enable row level security; alter table public.tickets enable row level security; alter table public.ticket_updates enable row level security;
create policy "reference read" on public.districts for select using (true); create policy "city reference read" on public.cities for select using (true);
create policy "profile own or admin read" on public.profiles for select using (id = auth.uid() or public.is_admin()); create policy "profile own insert" on public.profiles for insert with check (id = auth.uid()); create policy "profile own update" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());
create policy "member own or admin read" on public.members for select using (profile_id = auth.uid() or public.is_admin()); create policy "member own write" on public.members for insert with check (profile_id = auth.uid()); create policy "member own update" on public.members for update using (profile_id = auth.uid()) with check (profile_id = auth.uid());
create policy "ticket own or admin read" on public.tickets for select using (student_id = auth.uid() or public.is_admin()); create policy "ticket student insert" on public.tickets for insert with check (student_id = auth.uid()); create policy "ticket admin update" on public.tickets for update using (public.is_admin());
create policy "update own ticket read" on public.ticket_updates for select using (public.is_admin() or exists (select 1 from public.tickets where tickets.id = ticket_id and tickets.student_id = auth.uid())); create policy "admin update insert" on public.ticket_updates for insert with check (public.is_admin());

create or replace function public.track_ticket(lookup_ticket text, lookup_phone text) returns table(ticket_number text, status text, category text, created_at timestamptz, updates jsonb) language sql security definer set search_path = public as $$ select t.ticket_number, t.status, t.category, t.created_at, coalesce(jsonb_agg(jsonb_build_object('note', u.note, 'new_status', u.new_status, 'created_at', u.created_at) order by u.created_at) filter (where u.id is not null), '[]'::jsonb) from public.tickets t join public.profiles p on p.id = t.student_id left join public.ticket_updates u on u.ticket_id = t.id where t.ticket_number = lookup_ticket and p.phone = lookup_phone group by t.id $$;
grant execute on function public.track_ticket(text, text) to anon, authenticated;
insert into storage.buckets (id, name, public) values ('ticket-attachments', 'ticket-attachments', true) on conflict do nothing;
create policy "student upload attachment" on storage.objects for insert to authenticated with check (bucket_id = 'ticket-attachments' and (storage.foldername(name))[1] = auth.uid()::text);